---
- hosts: prod
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 10443
    vdom: "root"
   
  tasks:
    - name: "Nigel Allowed"
      fortinet.fortios.fortios_firewall_addrgrp:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_addrgrp:
          name: "Nigel Allowed"
          member: 
            - name: "*.nigelapi.com"
            - name: "*.nigel-app.com"
            - name: "reedompay-config.s3.us-east-2.amazonaws.com"
            - name: "nigel-on-premise.s3.us-east-2.amazonaws.com"
            - name: "nigel-desktop-pos.s3.us-east-2.amazonaws.com"
            - name: "538878852759.dkr.ecr.us-east-2.amazonaws.com"
            - name: "sqs.us-east-2.amazonaws.com"
            - name: "*.bugsnag.com"
            - name: "nigel-pos.es.us-east-2.aws.elastic-cloud.com"
            - name: "*.porteus-kiosk.org"
            - name: "*.42gears.com"
            - name: "suremdm-usstorage.s3.amazonaws.com"
            - name: "esper.cloud"
            - name: "dpccdownloads.esper.cloud"
            - name: "*.samsung.com"
            - name: "*.samsungknox.com"
            - name: "*.secb2b.com"
            - name: "*.googleapis.com"
            - name: "firebaseinstallations.googleapis.com"
            - name: "android.apis.google.com"
            - name: "www.google.com"
            - name: "connectivitycheck.gstatic.com"
            - name: "time.google.com"
            - name: "*.freedompay.com"
            - name: "*.freedompay.us"
            - name: "*.elementexpress.com"
            - name: "*.hostedpayments.com"
            - name: "*.vantiv.com"
            - name: "*.storedvalue.com"
            - name: "*.docker.io"
            - name: "ghcr.io"
            - name: "rancher.io"
            - name: "github.com"
            - name: "ipv4.connman.net"
            - name: "*.elastic.co"
            - name: "*.gcr.io"
            - name: "*.docker.com"
            - name: "acme-v02.api.letsencrypt.org"
            - name: "ns-735.awsdns-27.net"
            - name: "ns-1207.awsdns-22.org"
            - name: "ns-1913.awsdns-47.co.uk"
            - name: "ns-16.awsdns-02.com"
            - name: "ns-1667.awsdns-16.co.uk"
            - name: "ns-1372.awsdns-43.org"
            - name: "ns-393.awsdns-49.com"
            - name: "ns-965.awsdns-56.net"
            - name: "*.cloudfront.net"
            - name: "*.amazontrust.com"
            - name: "*.amazonaws.com"
            - name: "grafana.com"
            - name: "k8s.gcr.io"
            - name: "projectcalico.org"
            - name: "registry.k8s.io"
            - name: "raw.githubusercontent.com"
            - name: "spectrocloud.com"
            - name: "s3.amazonaws.com"
            - name: "quay.io"
            - name: "ecr.us-east-1.amazonaws.com"
            - name: "ecr.us-west-2.amazonaws.com"
            - name: "ntp.ubuntu.com"
            - name: "public.ecr.aws"
            - name: "acme-staging-v02.api.letsencrypt.org"
            - name: "*.appspot.com"
            - name: "*.k8s.io"
            - name: "*.pkg.dev"
            - name: "shoonyacloud.com"
            - name: "firebaseio.com"
            - name: "esper.io"
            - name: "crl.verisign.com"
            - name: "ops.api.olosandbox.com"
            - name: "ops.api.olo.com"
